# Copyright 2020, Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

{{- if eq .Values.type "NGINX" }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wcsitesinfra-ingress
  namespace: wcsites-ns
  annotations:
    nginx.org/proxy-connect-timeout: "1200s"
    nginx.org/proxy-read-timeout: "1200s"
    nginx.org/proxy-send-timeout: "1200s"
    nginx.com/sticky-cookie-services: "serviceName=wcsitesinfra-cluster-wcsites-cluster srv_id expires=1h path=/;"
spec:
  rules:
  - host: yourcompany-loadbalancer.com
    http:
      paths:
      - path: /console
        backend:
          serviceName: wcsitesinfra-adminserver
          servicePort: 7001
      - path: /em
        backend:
          serviceName: wcsitesinfra-adminserver
          servicePort: 7001
      - path: /wls-exporter
        backend:
          serviceName: wcsitesinfra-adminserver
          servicePort: 7001
      - path: /servicebus
        backend:
          serviceName: wcsitesinfra-adminserver
          servicePort: 7001
      - path: /sbconsole
        backend:
          serviceName: wcsitesinfra-adminserver
          servicePort: 7001
      - path: /sites
        backend:
          serviceName: wcsitesinfra-cluster-wcsites-cluster
          servicePort: 8001
      - path: /cas
        backend:
          serviceName: wcsitesinfra-cluster-wcsites-cluster
          servicePort: 8001
      - path: /wls-cat
        backend:
          serviceName: wcsitesinfra-cluster-wcsites-cluster
          servicePort: 8001
      - path:
        backend:
          serviceName: wcsitesinfra-cluster-wcsites-cluster
          servicePort: 8001
{{- end }}
